# -*- coding: utf-8 -*-
"""association_apriori.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wApnTZGAhFwQVn0cNGlwqYWyOKeEWHdb
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Market_Basket_Optimisation.csv', header = None)
transactions = []
for i in range(0, 7501):
  transactions.append([str(dataset.values[i,j]) for j in range(0, 20)])
  !pip install apyori
  from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2)

rules

