# -*- coding: utf-8 -*-
"""Copy of visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12o7XxvZ-Bi92GbNHOs_pUWTmMndMHqAi
"""

import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

data = sb.load_dataset("iris")

data.head()

data.shape

plt.scatter(data["sepal_length"],data["sepal_width"],color='red')
plt.show()
plt.title("scatter plot")
plt.xlabel("petal length")
plt.ylabel("petal width")

plt.hist(data['sepal_width'],bins=20)
plt.title("Histogram")
plt.xlabel("Petal width")
plt.ylabel("Frequency")
plt.show()

sb.boxplot(data=data,x='sepal_width')