# -*- coding: utf-8 -*-
"""eda-healthcarefinalll.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jEGN5dEqNfHECbq5CRMeZO8N9sOtG-rg
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset into a pandas DataFrame (Replace 'your_file.csv' with actual file name)
df = pd.read_csv('healthcare.csv')

# Display first few rows
print(df.head())

# --- Univariate Non-Graphical Analysis ---
# Summary statistics for numerical columns
print("\nSummary statistics:")
print(df.describe())

# Checking the count of unique values in categorical columns
print("\nUnique value counts in categorical columns:")
print(df[['Gender', 'Neighbourhood', 'Scholarship', 'Hipertension', 'Diabetes', 'Alcoholism', 'Handcap', 'SMS_received', 'No-show']].nunique())


# --- Multivariate Non-Graphical Analysis ---
# Drop non-numeric columns for correlation matrix calculation
numeric_df = df.select_dtypes(include=['int64', 'float64'])

# Correlation between numerical features
print("\nCorrelation matrix (numeric columns only):")
print(numeric_df.corr())

# Crosstab for Gender and No-show (to analyze how gender affects appointments missed)
print("\nCrosstab between Gender and No-show:")
print(pd.crosstab(df['Gender'], df['No-show']))

# --- Univariate Graphical Analysis ---
# Distribution of Age
plt.figure(figsize=(10, 6))
sns.histplot(df['Age'], bins=30, kde=True)
plt.title("Distribution of Age")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

# Count plot for Gender
plt.figure(figsize=(8, 6))
sns.countplot(x='Gender', data=df)
plt.title("Count of Gender")
plt.show()

# --- Multivariate Graphical Analysis ---
# Relationship between Age and No-show
plt.figure(figsize=(10, 6))
sns.boxplot(x='No-show', y='Age', data=df)
plt.title("Boxplot of Age vs No-show")
plt.show()

# Heatmap of correlations between numerical columns
plt.figure(figsize=(12, 8))
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm", linewidths=0.5)
plt.title("Correlation Heatmap (Numeric Columns Only)")
plt.show()

# Count plot of No-show based on scholarship, hypertension, and diabetes
plt.figure(figsize=(10, 6))
sns.countplot(x='No-show', hue='Scholarship', data=df)
plt.title("No-show by Scholarship")
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(x='No-show', hue='Hipertension', data=df)
plt.title("No-show by Hypertension")
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(x='No-show', hue='Diabetes', data=df)
plt.title("No-show by Diabetes")
plt.show()