# -*- coding: utf-8 -*-
"""decision_tree_dwm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LdF1Gxfgl6R7vO9COzeocu5NFPe_bxhY

# Decision Tree Classification

## Importing the libraries
"""

import pandas as pd
import numpy as np

data = pd.read_csv('preprocessing.csv')
x=data.drop(columns=['Purchased'])
y=data['Purchased']

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
columnstoimpute = ['Age','Salary']
imputer.fit(x[columnstoimpute])
x[columnstoimpute]=imputer.transform(x[columnstoimpute])


from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=np.array(le.fit_transform(y))