# -*- coding: utf-8 -*-
"""To use Explainable AI in healthcare for model interpretation..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jEGN5dEqNfHECbq5CRMeZO8N9sOtG-rg
"""

# Install required packages
!pip install transformers shap

import pandas as pd
from transformers import pipeline
import shap

# Sample data
data = {
    'feedback': [
        "The doctor was very helpful and attentive during my visit.",
        "I had a terrible experience with the hospital staff.",
        "The treatment was effective and I feel much better now.",
        "The waiting time was too long, and the nurses were rude.",
        "Great service! The team was very professional.",
        "I wouldn't recommend this clinic due to poor service."
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Load sentiment analysis pipeline
sentiment_model = pipeline("sentiment-analysis")

# Make predictions
predictions = sentiment_model(df['feedback'].tolist())

# Display predictions
for feedback, prediction in zip(df['feedback'], predictions):
    print(f"Feedback: {feedback}\nPredicted Sentiment: {prediction['label']} (Score: {prediction['score']:.4f})\n")

# Initialize SHAP
explainer = shap.Explainer(sentiment_model)
shap_values = explainer(df['feedback'].tolist())


shap.plots.text(shap_values)



